# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-11-26 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0002_remove_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
