# Generated by Django 2.1.14 on 2019-11-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
