# Generated by Django 2.1 on 2019-12-02 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0009_auto_20191202_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RS.Company'),
            preserve_default=False,
        ),
    ]
