# Generated by Django 2.1 on 2019-12-02 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0010_post_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='company_id',
        ),
    ]
