# Generated by Django 2.1 on 2019-12-02 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0012_auto_20191202_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='js_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS.JobSeeker'),
        ),
    ]
