# Generated by Django 2.1 on 2019-12-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0014_application_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='company_id',
        ),
    ]
