# Generated by Django 2.1 on 2019-12-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0015_remove_application_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RS.Company'),
            preserve_default=False,
        ),
    ]
