# Generated by Django 2.1 on 2019-12-03 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0016_application_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='company_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RS.Company'),
        ),
    ]
