# Generated by Django 2.1 on 2019-12-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RS', '0021_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profession',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='qualification',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
