# Generated by Django 2.1 on 2019-12-18 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RS', '0022_auto_20191205_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='applied',
            field=models.ManyToManyField(blank=True, related_name='applied', to=settings.AUTH_USER_MODEL),
        ),
    ]
